# Generated by Django 5.2.3 on 2025-06-30 20:26

from django.db import migrations


CATEGORIAS = [
    "Herramientas Manuales",
    "Materiales Básicos",
    "Equipos de Seguridad",
    "Tornillos y Anclajes",
    "Fijaciones",
    "Equipos de Medición",
]

def crear_categorias_iniciales(apps):
    Categoria = apps.get_model('app', 'Categoria')
    for nombre_categoria in CATEGORIAS:
        Categoria.objects.get_or_create(nombre=nombre_categoria)
    
def eliminar_categorias(apps):
    Categoria = apps.get_model('app', 'Categoria')
    Categoria.objects.filter(nombre__in=CATEGORIAS).delete()






class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario'),
    ]

    operations = [
    ]
