# Generated by Django 5.2.3 on 2025-07-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_proveedor_ubicacion_alertainventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertainventario',
            name='nivel',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracioninventario',
            name='stock_critico',
            field=models.PositiveIntegerField(default=5, help_text='Nivel crítico de stock'),
        ),
        migrations.AlterField(
            model_name='alertainventario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('resuelta', 'Resuelta'), ('ignorado', 'Ignorado')], default='pendiente', max_length=20),
        ),
    ]
